# Generated by Django 5.0.4 on 2024-04-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devdetails',
            fields=[
                ('dev_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.CharField(max_length=11)),
                ('dateofbirth', models.DateField()),
                ('designation', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('experience', models.CharField(max_length=20)),
            ],
        ),
    ]
