# Generated by Django 5.0.4 on 2024-04-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_devdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='user',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='employee_id',
        ),
    ]
