# Generated by Django 5.0.4 on 2024-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_employeedetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='jobtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='resume',
            field=models.ImageField(upload_to=''),
        ),
    ]
