# Generated by Django 5.0.4 on 2024-04-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_employeedetails_experience_employeedetails_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('employeeId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('homeAddress', models.TextField()),
                ('phoneNumber', models.CharField(max_length=11)),
                ('emailAddress', models.EmailField(max_length=50)),
                ('jobTitle', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('employmentType', models.CharField(max_length=20)),
                ('workLocation', models.CharField(max_length=50)),
                ('degreememo', models.FileField(upload_to='documents/')),
                ('sscmemo', models.FileField(upload_to='documents/')),
                ('idcard', models.FileField(upload_to='documents/')),
                ('resume', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='degree_certificate',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='employement_type',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='govt_id',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='jobtitle',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='ssc_certificate',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='devdetails',
            name='photo',
            field=models.ImageField(upload_to='developer_photos/'),
        ),
    ]
